apps/login_and_registration_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
]

apps/secrets_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logoff/$', views.logoff, name='logoff'),
    url(r'^new/$', views.logoff, name='logoff'),
]

dojo_secrets/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login_and_registration_app.urls', namespace='login_reg')),
    url(r'^secrets/', include('apps.secrets_app.urls', namespace='secrets')),
]

apps/login_and_registration_app/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt, re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

ONLY_LETTERS = re.compile(r'^[a-zA-Z]+$')

class UserManager(models.Manager):
    def register(self, data):
        errors = []

        if not data["first_name"]:
            errors.append("First Name is required")
        elif len(data["first_name"]) < 3:
            errors.append("First Name must be at least 2 characters")
        elif not ONLY_LETTERS.match(data["first_name"]):
            errors.append("First Name must contain only letters")

        if not data["last_name"]:
            errors.append("Last Name is required")
        elif len(data["last_name"]) < 2:
            errors.append("Last Name must be at least 2 characters")
        elif not ONLY_LETTERS.match(data["last_name"]):
            errors.append("Last Name must contain only letters")

        if not data["email"]:
            errors.append("Please enter an E-mail address")
        elif not EMAIL_REGEX.match(data["email"]):
            errors.append("Not a valid E-mail")
        elif User.objects.filter(email=data['email']):
            errors.append("Email is in use")

        if not data["password"]:
            errors.append("Please enter a password")
        elif len(data["password"]) < 8:
            errors.append("Password must be 8 characters")
        elif data["password"] != data["confirm"]:
            errors.append("Password and confirm password must match")

        response = {}

        password = data["password"].encode()
        hashed = bcrypt.hashpw(password, bcrypt.gensalt())

        if not errors:
            new_user = self.create(first_name=data['first_name'], last_name=data['last_name'], email=data['email'], password=hashed)
            response['added'] = True
            response['new_user'] = new_user
        else:
            response['added'] = False
            response['errors'] = errors
        return response

    def login(self, data):
        user = User.objects.filter(email=data['email'])

        if not user:
            return False
        else:
            user = user[0]

        password = data['password'].encode()

        if bcrypt.hashpw(password, user.password.encode()) == user.password.encode():
            return user
        else:
            return False


class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()
# Create your models here.

apps/login_and_registration_app/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages

def index(request):
    return render(request, 'login_and_registration_app/index.html')
# Create your views here.

def register(request):
    res = User.objects.register(request.POST)

    if res["added"]:
        request.session['user_id'] = res['new_user'].id
    else:
        for error in res["errors"]:
            messages.error(request, error)

    return redirect("login_reg:index")

def login(request):
    user = User.objects.login(request.POST)

    if user:
        request.session['user_id'] = user.id
    else:
        messages.error(request, "E-mail address or password incorrect")

    return redirect("secrets:index")

apps/secrets_app/views.py
from django.shortcuts import render, redirect
from ..login_and_registration_app.models import User
from django.contrib import messages

def index(request):
    if 'user_id' not in request.session:
        return redirect("login_reg:index")
    
    context = {
        'user': User.objects.get(id=request.session['user_id'])
    }
    return render(request, "secrets_app/index.html", context)

def logoff(request):
    request.session.clear()
    return redirect("login_reg:index")

# Create your views here.

apps/login_and_registration_app/templates/login_and_registration_app/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <div class="wrapper">
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <p>{{message}}</p>
                {% endif %}
            {% endfor %}
            <h1>Registration</h1>
            <form class="" action="{%url 'login_reg:register' %}" method="post">
                {% csrf_token %}
                First Name:<input type="text" name="first_name" value="">
                Last Name:<input type="text" name="last_name" value="">
                Email: <input type="text" name="email" value="">
                Password: <input type="password" name="password" value="">
                Confirm pw: <input type="password" name="confirm" value="">
                <input type="submit" name="register_button" value="Register">
            </form>
            <h1>Login</h1>
            <form class="" action="{%url 'login_reg:login' %}" method="post">
                {% csrf_token %}
                Email: <input type="text" name="email" value="">
                Password: <input type="password" name="password" value="">
                <input type="submit" name="login_button" value="Login">
            </form>
        </div>
    </body>
</html>

apps/login_and_registration_app/templates/login_and_registration_app/success.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <div class="wrapper">
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <h1>{{message}}</h1>
                {% endif %}
            {% endfor %}
            <p></p>
        </div>
    </body>
</html>

apps/secrets_app/templates/secrets_app/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
        <title></title>
         {% load humanize %}
    </head>
    <body>
        <div class="wrapper">
            <form class="" action="{%url 'secrets:logoff' %}" method="post">
                {% csrf_token %}
                <input type="submit" name="" value="Log off">
            </form>
            <h4>Hello, {{user.first_name}}</h4>
            <form action="/secrets/new" method="post">
              {% csrf_token %}
                <textarea name="textbox" rows="8" cols="40" placeholder="Your secret here..."></textarea>
                <button type="submit" name="post">Post</button>
            </form>
            <h4>Recent Secrets:</h4>
            {% if secrets %}
                {% for secret in secrets %}
                    <p>
                    {{secret.content}} ({{secret.created_at|naturaltime}}) <span class='italics'>{{secret.like_users.count}} likes</span>
                    {% if secret.secret_user.id == request.session.userid %}
                        <span class='green'>You posted this</span>
                        <a href="/secrets/destroy_user/{{secret.id}}">Delete</a>
                    {% else %}
                        {% if user in secret.like_users.all %}
                            <span class='green'>You liked this</span>
                        {% else %}
                            <a class='green' href="/secrets/like_user/{{secret.id}}">Like</a>
                        {% endif %}
                    {% endif %}
                    </p>
                {% endfor %}
            {% endif %}
        </div>
    </body>
</html>